In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../dataset/processed/base_dataset.csv")

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
print("="*50)
print("Dataset Shape")
print("="*50)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

==================================================
Dataset Shape
==================================================
Rows    : 5572
Columns : 2

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   str
 1   message  5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB

In [5]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [6]:
duplicates = df.duplicated().sum()

print("Duplicate Records :", duplicates)

Duplicate Records : 403

In [7]:
df.drop_duplicates(inplace=True)

df.reset_index(drop=True, inplace=True)

print("New Shape :", df.shape)

New Shape : (5169, 2)

In [8]:
df["label"].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

In [9]:
distribution = (
    df["label"]
    .value_counts(normalize=True)
    * 100
)

distribution.round(2)

label
ham     87.37
spam    12.63
Name: proportion, dtype: float64

In [10]:
df["message_length"] = df["message"].apply(len)

df.head()

  label                                            message  message_length
0   ham  Go until jurong point, crazy.. Available only ...             111
1   ham                      Ok lar... Joking wif u oni...              29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             155
3   ham  U dun say so early hor... U c already then say...              49
4   ham  Nah I don't think he goes to usf, he lives aro...              61

In [11]:
df["message_length"].describe()

count    5169.000000
mean       78.977945
std        58.236293
min         2.000000
25%        36.000000
50%        60.000000
75%       117.000000
max       910.000000
Name: message_length, dtype: float64

In [12]:
longest = df["message_length"].max()

print("Longest Message Length :", longest)

Longest Message Length : 910

In [13]:
shortest = df["message_length"].min()

print("Shortest Message Length :", shortest)

Shortest Message Length : 2

In [14]:
average = df["message_length"].mean()

print("Average Message Length :", round(average,2))

Average Message Length : 78.98

In [15]:
df.sample(10, random_state=42)

     label                                            message  message_length
1566   ham                      Did u download the fring app?              29
1988   ham  Pass dis to all ur contacts n see wat u get! R...             276
1235   ham                                              Ok...               5
2868   ham                     Am in film ill call you later.              30
3435   ham  Sorry, left phone upstairs. OK, might be hecti...             107
1471  spam  URGENT! Your Mobile No was awarded a å£2,000 B...             159
1129   ham  Yun buying... But school got offer 2000 plus o...              52
3747  spam  Ringtone Club: Gr8 new polys direct to your mo...              63
3047   ham    Don know:)this week i'm going to tirunelvai da.              47
530    ham  I am in tirupur da, once you started from offi...              57

In [16]:
df.to_csv("../dataset/processed/understanding_dataset.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.