In [1]:
import pandas as pd
import numpy as np

import re
import string

import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../dataset/processed/eda_dataset.csv")

df.head()

  label                                            message  message_length
0   ham  Go until jurong point, crazy.. Available only ...             111
1   ham                      Ok lar... Joking wif u oni...              29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             155
3   ham  U dun say so early hor... U c already then say...              49
4   ham  Nah I don't think he goes to usf, he lives aro...              61

In [3]:
lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words("english"))

In [4]:
df["clean_message"] = df["message"].str.lower()

In [5]:
def remove_html(text):
    return re.sub(r"<.*?>", "", text)

df["clean_message"] = df["clean_message"].apply(remove_html)

In [6]:
def remove_urls(text):
    return re.sub(r"http\S+|www\S+", "", text)

df["clean_message"] = df["clean_message"].apply(remove_urls)

In [7]:
def remove_emails(text):
    return re.sub(r"\S+@\S+", "", text)

df["clean_message"] = df["clean_message"].apply(remove_emails)

In [8]:
def remove_numbers(text):
    return re.sub(r"\d+", "", text)

df["clean_message"] = df["clean_message"].apply(remove_numbers)

In [9]:
def remove_punctuation(text):
    return text.translate(
        str.maketrans("", "", string.punctuation)
    )

df["clean_message"] = df["clean_message"].apply(remove_punctuation)

In [12]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91953\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\91953\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [13]:
def tokenize(text):
    return nltk.word_tokenize(text)

df["tokens"] = df["clean_message"].apply(tokenize)

In [14]:
def remove_stopwords(tokens):
    return [
        word
        for word in tokens
        if word not in stop_words
    ]

df["tokens"] = df["tokens"].apply(remove_stopwords)

In [15]:
def lemmatize(tokens):
    return [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

df["tokens"] = df["tokens"].apply(lemmatize)

In [16]:
df["clean_message"] = df["tokens"].apply(
    lambda x: " ".join(x)
)

In [17]:
df["clean_message"] = (
    df["clean_message"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [18]:
comparison = df[
    ["message", "clean_message"]
]

comparison.head(10)

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think go usf life around though
5,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey darling week word back id like fun...
6,Even my brother is not like to speak with me. ...,even brother like speak treat like aid patent
7,As per your request 'Melle Melle (Oru Minnamin...,per request melle melle oru minnaminunginte nu...
8,WINNER!! As a valued network customer you have...,winner valued network customer selected receiv...
9,Had your mobile 11 months or more? U R entitle...,mobile month u r entitled update latest colour...

In [19]:
df.to_csv(
    "../dataset/processed/preprocessed_dataset.csv",
    index=False
)

print("Preprocessed dataset saved successfully.")

Preprocessed dataset saved successfully.